// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0mBHb5w49PpjYZm_wnPmEyLPj09IE7EA',
    appId: '1:352654640210:web:3f7970180e5205b2bf8b8b',
    messagingSenderId: '352654640210',
    projectId: 'lab5-a1454',
    authDomain: 'lab5-a1454.firebaseapp.com',
    databaseURL: 'https://lab5-a1454-default-rtdb.firebaseio.com',
    storageBucket: 'lab5-a1454.appspot.com',
    measurementId: 'G-JFWTD9RL1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTPwHzpPxpfTDG-RIw0PbnQjyf5JpOL5Q',
    appId: '1:352654640210:android:d4bf2a0c1d504f85bf8b8b',
    messagingSenderId: '352654640210',
    projectId: 'lab5-a1454',
    databaseURL: 'https://lab5-a1454-default-rtdb.firebaseio.com',
    storageBucket: 'lab5-a1454.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIfeKMoGxlRBS_tWss7i_C0LrS5QswRFs',
    appId: '1:352654640210:ios:41671abe25c92258bf8b8b',
    messagingSenderId: '352654640210',
    projectId: 'lab5-a1454',
    databaseURL: 'https://lab5-a1454-default-rtdb.firebaseio.com',
    storageBucket: 'lab5-a1454.appspot.com',
    iosClientId: '352654640210-jif8p5alna0sv55tpjse16sju2cm7os5.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIfeKMoGxlRBS_tWss7i_C0LrS5QswRFs',
    appId: '1:352654640210:ios:41671abe25c92258bf8b8b',
    messagingSenderId: '352654640210',
    projectId: 'lab5-a1454',
    databaseURL: 'https://lab5-a1454-default-rtdb.firebaseio.com',
    storageBucket: 'lab5-a1454.appspot.com',
    iosClientId: '352654640210-jif8p5alna0sv55tpjse16sju2cm7os5.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
